#!/bin/bash
# ============================================================================
# Claude Code Bedrock Configuration Script
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default values
AWS_REGION="${AWS_REGION:-us-east-1}"
ANTHROPIC_MODEL="${ANTHROPIC_MODEL:-global.anthropic.claude-sonnet-4-5-20250929-v1:0}"
ANTHROPIC_SMALL_FAST_MODEL="${ANTHROPIC_SMALL_FAST_MODEL:-us.anthropic.claude-haiku-4-5-20251001-v1:0}"
CLAUDE_CODE_MAX_OUTPUT_TOKENS="${CLAUDE_CODE_MAX_OUTPUT_TOKENS:-4096}"
MAX_THINKING_TOKENS="${MAX_THINKING_TOKENS:-1024}"

echo -e "${GREEN}🚀 Claude Code Bedrock Configuration${NC}"
echo "=================================="
echo ""

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check prerequisites
echo -e "${YELLOW}Checking prerequisites...${NC}"

if ! command_exists aws; then
    echo -e "${RED}❌ AWS CLI is not installed${NC}"
    echo "Install it from: https://aws.amazon.com/cli/"
    exit 1
fi

if ! aws sts get-caller-identity >/dev/null 2>&1; then
    echo -e "${RED}❌ AWS credentials not configured${NC}"
    echo "Run: aws configure"
    exit 1
fi

echo -e "${GREEN}✅ Prerequisites check passed${NC}"
echo ""

# Interactive configuration
read -p "AWS Region [${AWS_REGION}]: " input_region
AWS_REGION="${input_region:-$AWS_REGION}"

read -p "Anthropic Model [${ANTHROPIC_MODEL}]: " input_model
ANTHROPIC_MODEL="${input_model:-$ANTHROPIC_MODEL}"

read -p "Small Fast Model [${ANTHROPIC_SMALL_FAST_MODEL}]: " input_small_model
ANTHROPIC_SMALL_FAST_MODEL="${input_small_model:-$ANTHROPIC_SMALL_FAST_MODEL}"

read -p "Max Output Tokens [${CLAUDE_CODE_MAX_OUTPUT_TOKENS}]: " input_max_tokens
CLAUDE_CODE_MAX_OUTPUT_TOKENS="${input_max_tokens:-$CLAUDE_CODE_MAX_OUTPUT_TOKENS}"

read -p "Max Thinking Tokens [${MAX_THINKING_TOKENS}]: " input_thinking_tokens
MAX_THINKING_TOKENS="${input_thinking_tokens:-$MAX_THINKING_TOKENS}"

# Create .env file
ENV_FILE="${PROJECT_ROOT}/.env.bedrock"

cat > "$ENV_FILE" <<EOF
# Claude Code Bedrock Configuration
# Generated by configure-bedrock.sh on $(date)

# Enable Bedrock usage
export CLAUDE_CODE_USE_BEDROCK=1

# AWS Configuration
export AWS_REGION=${AWS_REGION}

# Claude Models
export ANTHROPIC_MODEL=${ANTHROPIC_MODEL}
export ANTHROPIC_SMALL_FAST_MODEL=${ANTHROPIC_SMALL_FAST_MODEL}

# Token Limits
export CLAUDE_CODE_MAX_OUTPUT_TOKENS=${CLAUDE_CODE_MAX_OUTPUT_TOKENS}
export MAX_THINKING_TOKENS=${MAX_THINKING_TOKENS}
EOF

echo ""
echo -e "${GREEN}✅ Configuration saved to ${ENV_FILE}${NC}"
echo ""
echo "To use this configuration, run:"
echo -e "${YELLOW}  source ${ENV_FILE}${NC}"
echo ""
echo "Or add to your shell profile (~/.bashrc, ~/.zshrc):"
echo -e "${YELLOW}  source ${ENV_FILE}${NC}"

# Verify Bedrock access
echo ""
echo -e "${YELLOW}Verifying Bedrock access...${NC}"

if aws bedrock list-foundation-models \
    --region "$AWS_REGION" \
    --query 'modelSummaries[?providerName==`Anthropic`]' \
    --output json >/dev/null 2>&1; then
    echo -e "${GREEN}✅ Bedrock access verified${NC}"
else
    echo -e "${RED}⚠️  Warning: Could not verify Bedrock access${NC}"
    echo "Make sure Bedrock is enabled in your AWS account"
fi

echo ""
echo -e "${GREEN}🎉 Configuration complete!${NC}"
